apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
          - name: staging
          - name: prod
  template:
    metadata:
      name: "nginx-{{name}}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "nginx-{{name}}"
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 21.0.8
        helm:
          values: |
            service:
              type: NodePort
            replicaCount: 1
      # syncPolicy:
      #   automated:
      #     prune: true
      #     selfHeal: true
